@startuml
!include ../src/Common.puml
''----------------------------------------------------------------------------------------------------------------------
'' Тесты
''----------------------------------------------------------------------------------------------------------------------
!procedure PlantUmlExtensionVer_returns_semantic_version()
    '' Arrange, Act
    !$actual = $PlantUmlExtensionVer()

    '' Assert
    !assert %size(%splitstr($actual, ".")) == 3
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Запуск тестов
''----------------------------------------------------------------------------------------------------------------------
PlantUmlExtensionVer_returns_semantic_version()
''----------------------------------------------------------------------------------------------------------------------
caption OK
@enduml