@startuml
!include ../src/Utils.puml
''----------------------------------------------------------------------------------------------------------------------
'' Тесты
''----------------------------------------------------------------------------------------------------------------------
!procedure Format_should_convert_values_to_string_based_on_specified_placeholders()
    '' Arrange, Act
    !$actual = $Format("This is %1 with arguments %2 and %3.", "expression", "x", "y")

    '' Assert
    !assert "This is expression with arguments x and y." == $actual
!endprocedure
''----------------------------------------------------------------------------------------------------------------------
'' Запуск тестов
''----------------------------------------------------------------------------------------------------------------------
Format_should_convert_values_to_string_based_on_specified_placeholders()
''----------------------------------------------------------------------------------------------------------------------
caption OK
@enduml