@startuml
''----------------------------------------------------------------------------------------------------------------------
'' Registration
''----------------------------------------------------------------------------------------------------------------------

''----------------------------------------------------------------------------------------------------------------------
'' Including
''----------------------------------------------------------------------------------------------------------------------

''----------------------------------------------------------------------------------------------------------------------
'' Alignment
''----------------------------------------------------------------------------------------------------------------------

''----------------------------------------------------------------------------------------------------------------------
'' Rendering
''----------------------------------------------------------------------------------------------------------------------

''----------------------------------------------------------------------------------------------------------------------
'' Assembling
''----------------------------------------------------------------------------------------------------------------------


@enduml