@startuml

!global $COLOR = {
    "Undefined": "transparent",
    "Entity": "LightYellow",
    "Abstract": "Azure",
    "Alert": "Red",
    "Component": "Blue"
}

!include Common.puml

skinparam minClassWidth 80
skinparam nodesep 10
skinparam ranksep 10

!procedure $Table($columns, $rows, $dataAccessor, $cellRenderer)
    !$c = 0
    !$index = 0
    !while $c < $columns
        !$r = 0
        !while $r < $rows
            !$pair = %call_user_func($dataAccessor, $index)
            !if $pair != 0
                %invoke_procedure($cellRenderer, $pair.Name, $pair.Value)
            !else
                %invoke_procedure($cellRenderer, $Format("%1-%2", $c, $r), "transparent")
            !endif
            !$index = $index + 1
            !$r = $r + 1
        !endwhile
        !$c = $c + 1
    !endwhile
!endprocedure


!function $GetColorByIndex($index, $undefined=0)
    !$n = 0
    !foreach $key in %get_json_keys($COLOR)
        !if $n == $index
            !$pair = %str2json($Format('{"Name": "%1", "Value": "%2"}', $key, $COLOR[$key]))
            !return $pair
        !endif
        !$n = $n + 1
    !endfor
    !return $undefined
!endfunction


!procedure $DrawCell($name, $color)
    rectangle "$name" #$color
!endprocedure

'' $Table(4, 4, $GetColorByIndex, $DrawCell)

@enduml