@startuml
!include Utils.puml
''----------------------------------------------------------------------------------------------------------------------
'' Get PlantUml Extension library version.
'' example: !$ver = $PlantUmlExtensionVer()
!function $PlantUmlExtensionVer()
    !$ver = %load_json("../version.json")
    !return $Format("%1.%2.%3", $ver.Major, $ver.Minor, $ver.Patch)
!endfunction
''----------------------------------------------------------------------------------------------------------------------
@enduml