name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Install GitVersion
#        uses: gittools/actions/gitversion/setup@v0.9.15
#        with:
#          versionSpec: '5.x'
#
#      - name: Generate Version Info
#        run: gitversion /output json /outputfile version.json
#
#      - name: Commit version.json
#        run: |
#          git config --local user.email "actions@github.com"
#          git config --local user.name "GitHub Actions"
#          git add version.json
#          git commit -m "ci: update version [skip ci]"
#          git push origin HEAD:main
#
#      - name: Extract Version
#        id: set-version
#        run: |
#          MAJOR=$(jq -r '.Major' version.json)
#          MINOR=$(jq -r '.Minor' version.json)
#          echo "VERSION=v$MAJOR.$MINOR" >> $GITHUB_ENV
#          echo "ZIP_NAME=PlantUML-Extension-$VERSION.zip" >> $GITHUB_ENV
#
#      - name: Create Archive
#        run: |
#          mkdir -p archive
#          find src -name '*.puml' -exec cp --parents '{}' archive/ \;
#          cp version.json archive/
#          zip -r ${{ env.ZIP_NAME }} archive/*
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.ZIP_NAME }}
#          path: ${{ env.ZIP_NAME }}