name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ksm2/archive-action@v1
        with:
          # The directory to archive from
          root-directory: ./src
          include: "**/*.puml"
          format: "zip"
          name: "PUML-Ext"
    
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
