name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.2.x'
          
      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.2.0

      - run: |
          echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
        name: Display GitVersion variables (without prefix)

      - name: Create version.json
        run: |
          echo '{
            "Major": ${{ steps.gitversion.outputs.major }},
            "Minor": ${{ steps.gitversion.outputs.minor }},
            "Patch": ${{ steps.gitversion.outputs.patch }}
          }' > version.json
