name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Find and package PlantUML files
      id: package
      run: |
        find . -type f \( -name '*.puml' -o -name '*.plantuml' \) > filelist.txt
        
        if [ ! -s filelist.txt ]; then
          echo "No PlantUML files found. Skipping archive creation."
          exit 0
        fi

        zip -r PlantUml-Extension.zip -@ < filelist.txt

    - uses: actions/upload-artifact@v4
      with:
        name: PlantUml-Extension
        path: '**/*.zip'